package:
    type:           yii2-extension
    name:           yii2-asset-hiqdev
    title:          'HiQDev assets: params, images and more'
    headline:       HiQDev assets
    keywords:       hiqdev, asset, extension, yii2
    namespace:      hiqdev\assets\hiqdev
    description:    |
        [HiQDev] is software development and consulting company.

        This package provides assets shareable between different HiQDev projects:

        - logos and css bundled with yii2 asset bundle
        - reusable params see [src/config/params.php]
        - translations

        [HiQDev]: https://hiqdev.com/
